### ISSUE TITLE
ICollection<string> not serializing properly

### ISSUE THREAD

**Issue by kylednoland** [aliencube/AzureFunctions.Extensions#100]
## Issue
When I have a model item that includes an ICollection<string> the resulting OpenAPI document reference results in an ICollection`1 instead. It looks like current logic covers List<T>, IList<T>, IEnumerable<T>, but not ICollection<T>.

## Repro Steps
Add an `OpenApiResponseWithBody` attribute to a Function which contains a referencing Type that contains an ICollection<string>

**Comment by justinyoo** [comment]
@kylednoland Thanks for raising the issue! I'll have a look and fix it.

**Comment by justinyoo** [comment]
@kylednoland This has been fixed on [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0)

**Comment by kylednoland** [comment]
Confirmed fixed in v3. Thanks @justinyoo!
