### ISSUE TITLE
Enum to string conversion doesn't seem to work

### ISSUE THREAD

**Issue by kaluznyt** [aliencube/AzureFunctions.Extensions#102]
Hi, 

Thanks for great package !

I'm trying to achieve something, namely, I have a request/response model wich have some enums, and would like to display the enum options as strings. 

In the docs I found that decorating the enum property with JsonConverter(typeof(StringEnumConverted)) should be sufficient.
https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md#jsonconverter

But it isn't in my case, I added the JsonProperty to change the name, and this one was effective:
![image](https://user-images.githubusercontent.com/572605/89186302-e2351c00-d59b-11ea-8324-8d9da088b913.png)

![image](https://user-images.githubusercontent.com/572605/89186319-e95c2a00-d59b-11ea-9381-2a1255319484.png)

I tried JsonConverter from both Newtonsoft and System.Text.Json...

I'm on version 3.0.0 of the Aliencube.AzureFunctions.Extensions.OpenAPI

I might be doing something wrong. 

Thanks for any help 
Tomasz

**Comment by justinyoo** [comment]
@kaluznyt Thanks for the issue. Can you please try like:

```csharp
[JsonConverter(typeof(StringEnumConverter))]
public enum Status
{
    OK,
    Done
}
```

https://github.com/aliencube/AzureFunctions.Extensions/blob/c53adaff65b33bacf7780272e3e36aaf87c2cf6f/samples/Aliencube.AzureFunctions.FunctionApp.Models/StringEnum.cs#L9-L11

**Comment by justinyoo** [comment]
It doesn't support `System.Text.Json` package yet, as Azure Functions runtime doesn't support it.

**Comment by kaluznyt** [comment]
@justinyoo Thank you that works fine ! I thought I tried that, but perhaps I got a reference to System.Text.Json JsonConverter instead of Newtonsoft earlier and didn't see any effect :( Thanks again!
