### ISSUE TITLE
Support for triggers from multiple Assemblies

### ISSUE THREAD

**Issue by ELimburg** [aliencube/AzureFunctions.Extensions#105]
I would like to have one OpenAPI spec for triggers from multiple assemblies. Is that somehow possible?
Azure Functions do support it by setting the property `<FunctionsInDependencies>true</FunctionsInDependencies>`.

**Comment by justinyoo** [comment]
@ELimburg Thanks for the issue. Would you please elaborate your question?

**Comment by ELimburg** [comment]
@justinyoo I have attached a small test function app that shows this issue.
I have two projects. The main functionapp and a library with another function.
When the the functionapp is started both functions are started and are running fine.
The issue is that the swagger docs only show the function from the main project and not the library.

[ExampleAppSwaggerMultipleAssemblies.zip](https://github.com/aliencube/AzureFunctions.Extensions/files/5041828/ExampleAppSwaggerMultipleAssemblies.zip)

**Comment by justinyoo** [comment]
Let me have a look. I hasn't been sure what it exactly means.

**Comment by justinyoo** [comment]
I'll close it for now because I don't fully understand the issue. If you still want to discuss, please try the other repo: https://github.com/Azure/azure-functions-openapi-extension
