### ISSUE TITLE
"An item with the same key has already been added" for the generic value type of a dictionary

### ISSUE THREAD

**Issue by Archomeda** [aliencube/AzureFunctions.Extensions#109]
Very similar to #61.

Example:
```cs
public class ClassA
{
    public IDictionary<string, ClassB> Values { get; set; }
}

public class ClassB
{
    // ...
}

[OpenApiRequestBody("application/json", typeof(ClassA), Required = true)]
[OpenApiResponseWithBody(HttpStatusCode.OK, "application/json", typeof(IDictionary<string, ClassB>))]
public Task<IActionResult> Run([HttpTrigger] HttpRequest req)
{
    // ...
}
```

This throws `An item with the same key has already been added. Key: classB.`

**Comment by justinyoo** [comment]
@Archomeda Thanks for the issue! I was able to reproduce the issue. A fix will be added soon.

**Comment by justinyoo** [comment]
A new release has been published: https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.1.0

**Comment by justinyoo** [comment]
I'll close this issue. But if you still experience the same issue, please feel free to re-open it.

**Comment by bseng** [comment]
Hi,

I've a similar issue.

The code below will throw `An item with the same key has already been added. Key: classB.`

```cs
public class RequestDto
{
     public classB One {get; set;}
     public classB Two {get; set;}
}
```
