### ISSUE TITLE
Support for response headers

### ISSUE THREAD

**Issue by Archomeda** [aliencube/AzureFunctions.Extensions#110]
I have found the ability to define request headers in `OpenApiParameterAttribute`, but I haven't found a way to define headers for responses. Have I missed this, or is it currently not supported? If the latter, can support for this be added?

**Comment by ccruden-shookiot** [comment]
Perhaps you're looking for the OpenApiResponseWithBodyAttribute and OpenApiResponseWithoutBodyAttribute classes? Bottom of the page [here](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi-core.md).

**Comment by Archomeda** [comment]
I'm already using those, but there's no support for setting response headers there.

**Comment by justinyoo** [comment]
@Archomeda It's not supported yet

**Comment by justinyoo** [comment]
Reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#responseObject

**Comment by justinyoo** [comment]
Please check WIP at https://github.com/Azure/azure-functions-openapi-extension/issues/38
