### ISSUE TITLE
how to specify file upload parameter

### ISSUE THREAD

**Issue by ma3yta** [aliencube/AzureFunctions.Extensions#111]
https://swagger.io/docs/specification/2-0/file-upload/
https://swagger.io/docs/specification/describing-request-body/file-upload/

``[OpenApiRequestBody("multipart/form-data", typeof(IFormFile))]`` doesn't work

**Comment by justinyoo** [comment]
@Ma3yTa The content type of `multipart/form-data` is not supported yet.

**Comment by justinyoo** [comment]
Related to #71

**Comment by justinyoo** [comment]
Please follow https://github.com/Azure/azure-functions-openapi-extension/issues/18 for future WIP
