### ISSUE TITLE
Primitive types declarations

### ISSUE THREAD

**Issue by baltuonis** [aliencube/AzureFunctions.Extensions#112]
Hi, recently we've upgraded to the latest (v3) Aliencube.AzureFunctions.Extensions.OpenApi.Core package and we are seeing a strange behaviour regarding the primitive types declarations which breaks our ApiManagement ARM templates.

So previously responses were looking like this:

```json
{
  "400": {
  "description": "Bad Request",
            "schema": {
              "type": "string"
             }
       }
}
```

but now it looks like this:

```json
 "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/string"
            }
        }
```
Which I assume is not the correct behaviour...
Also `string` does not exist in definitions

Same happens with `boolean`.

However query parameters are being declared correctly `"type": "string"`.

Can we somehow fix this behaviour?

**Comment by justinyoo** [comment]
@baltuonis Thanks for the issue. Could you please show how I can reproduce this issue?

**Comment by wouter-droog** [comment]
@justinyoo I'm getting the same behavior.

the behavior occurs when defining the bodyType in OpenApiResponseWithBody attribute.

Reproduction steps:
with bool
```
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: MediaTypeNames.Text.Plain, bodyType: typeof(bool),
            Summary = "successful operation", Description = "successful operation")]
```
with string
```
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: MediaTypeNames.Application.Json, bodyType: typeof(string),
            Summary = "successful operation", Description = "successful operation")]
```

**Comment by justinyoo** [comment]
This fix has been released: https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.1.1

I'm going to close this issue. If you still have an issue, feel free to open this again.
