### ISSUE TITLE
List type declarations

### ISSUE THREAD

**Issue by baltuonis** [aliencube/AzureFunctions.Extensions#113]
Hi,

We've updated to the latest 3.0.0 version of OpenAPI generator and it creates some really strange unspecified definitions for lists.

Example:

```json
 {
      "VehicleQuestionAnswerCollection": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/IList`1"
          }
        },
}
```

The `"$ref": "#/definitions/IList`1"` part does not exist in definitions and it can't be recognized.

**Comment by justinyoo** [comment]
@baltuonis Thanks for the issue! It seems that your `VehicleQuestionAnswerCollection` is a dictionary type like `Dictionary<string, IList<T>>`. Can you please provide the class definition?

**Comment by baltuonis** [comment]
This is the definition 

```csharp
IDictionary<Guid, IList<IQuestionAnswer>>VehicleQuestionAnswerCollection { get; }
```

**Comment by justinyoo** [comment]
This fix has been released: https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.1.1

I'm going to close this issue. If you still have an issue, feel free to open this again.
