### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by tsolbjor** [aliencube/AzureFunctions.Extensions#115]
If you have multiple properties of the same complex type in response body ObjectTypeVisitor.ProcessProperties failes with:

`An item with the same key has already been added. Key: <typename>`

**Comment by tsolbjor** [comment]
PR that solves is in #114

**Comment by justinyoo** [comment]
@tsolbjor Thanks for the issue! It's been merged and will be released soon.

**Comment by justinyoo** [comment]
This fix has been released: https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.1.1

I'm going to close this issue. If you still have an issue, feel free to open this again.
