### ISSUE TITLE
Add broader support for Microsoft's Custom Connector annotations

### ISSUE THREAD

**Issue by hajekj** [aliencube/AzureFunctions.Extensions#116]
There are already [samples](https://devkimchi.com/2020/07/15/creating-custom-connector-from-azure-functions-with-swagger/) how to make use of this library to make some more advanced annotations for Custom Connectors in Logic Apps or Power Automate.

It would be really cool to get support for trigger annotations along with dynamic schema and so on. Microsoft has it quite well documented here: https://docs.microsoft.com/en-us/connectors/custom-connectors/openapi-extensions

In the past, there was a project called [T-Rex](https://github.com/nihaue/TRex) which did exactly that, however it was only for ASP.NET on .NET Framework and doesn't support ASP.NET Core or Azure Functions.

**Comment by justinyoo** [comment]
@hajekj Thanks for the issue! I'll chase this up.

**Comment by justinyoo** [comment]
Please follow for future WIP: https://github.com/Azure/azure-functions-openapi-extension/issues/36
