### ISSUE TITLE
byte[] in Response object for OpenApiResponseWithBody triggers an error

### ISSUE THREAD

**Issue by grik001** [aliencube/AzureFunctions.Extensions#119]
Hi,

I am not sure if everything is correct in my implementation. But it seems that when I use a byte[] in a return object I get the following error:

![image](https://user-images.githubusercontent.com/27157850/92113968-67585e80-edf0-11ea-96b0-0faa5bd2508a.png)
![image](https://user-images.githubusercontent.com/27157850/92114173-b69e8f00-edf0-11ea-9fac-d410eb1d4f9c.png)
![image](https://user-images.githubusercontent.com/27157850/92113724-07fa4e80-edf0-11ea-8cb1-2d73342fba16.png)

If I remove the byte[] array, the swagger/openapi are generated as expected.

**Comment by justinyoo** [comment]
@grik001 Thanks for the issue! The `byte` type is not supported at the moment.

**Comment by nikolic-m** [comment]
@grik001 Hi,

I had the same issue and I resolved it by adding ByteVisitor manually to the visitor collection when initializing the document since I noticed that it was missing in the source code. It's not the perfect solution though. Hope it helps you as well.

Code example below:

``` csharp
public class ByteTypeVisitor : TypeVisitor
    {
        public ByteTypeVisitor(VisitorCollection visitorCollection)
            : base(visitorCollection)
        {
        }

        public override bool IsVisitable(Type type)
        {
            return IsVisitable(type, TypeCode.Byte);
        }

        public override void Visit(
            IAcceptor acceptor,
            KeyValuePair<string, Type> type,
            NamingStrategy namingStrategy,
            params Attribute[] attributes)
        {
            Visit(acceptor, name: type.Key, title: null, dataType: "string", dataFormat: "byte", attributes: attributes);
        }

        public override bool IsParameterVisitable(Type type)
        {
            return base.IsVisitable(type);
        }

        public override OpenApiSchema ParameterVisit(Type type, NamingStrategy namingStrategy)
        {
            return ParameterVisit(dataType: "string", dataFormat: "byte");
        }

        public override bool IsPayloadVisitable(Type type)
        {
            return IsVisitable(type);
        }

        public override OpenApiSchema PayloadVisit(Type type, NamingStrategy namingStrategy)
        {
            return PayloadVisit(dataType: "string", dataFormat: "byte");
        }
    }
```

**Comment by justinyoo** [comment]
I'll start having a look soon on the other repo: https://github.com/Azure/azure-functions-openapi-extension

**Comment by punthoofd07** [comment]
Following, would like this feature as well since I have the same issue.
Thanks
