### ISSUE TITLE
How is AppSettings class implemented?

### ISSUE THREAD

**Issue by object** [aliencube/AzureFunctions.Extensions#12]
Can you explain or perhaps extend examples with the implementation of AppSettings? Since there is no such class on .NET Core it can be useful to provide the implementation.

Thank you for a great library.

**Comment by object** [comment]
I've found implementation of this class in your source. Closing the issue.

**Comment by justinyoo** [comment]
@object Thanks for pointing out this. Let me have a look whether I can squeeze this implementation into the library as a base class or not.

**Comment by justinyoo** [comment]
@object I've listed another package for this:

https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.Configuration.AppSettings

And based on this, the Extensions.OpenApi has been updated to 1.4.2.

**Comment by object** [comment]
Perfect! Thanks a lot!
