### ISSUE TITLE
Using custom List types in OpenApiRequestBody and OpenApiResponseWithBody bodyType parameter

### ISSUE THREAD

**Issue by obautista** [aliencube/AzureFunctions.Extensions#120]
Is it possible the OpenApiRequestBody and OpenApiResponseWithBody reference custom list types?  For example:

`[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(SearchSpecificationDto<AddressDto>), Required = true, Description = "SearchSpecificationDto of type AddressDto")]`

`[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(SearchResultDto<AddressDto>), Summary = "SearchResultDto of type AddressDto", Description = "SearchResultDto of type AddressDto")]`

Notice SearchSpecificationDto<AddressDto> and SearchResultDto<AddressDto>.  It is generating:

`"/search/addresses": {
	"post": {
		"tags": [
			"SearchAddressFunction"
		],
		"summary": "SearchAddressFunction",
		"description": "SearchAddressFunction",
		"operationId": "searchAddressFunction",
		"requestBody": {
			"content": {
				"application/json": {
					"schema": {
					"$ref": "#/components/schemas/searchSpecificationDto1"
					}
				}
			},
			"required": true
		}
	}
}`

The problem is "searchSpecificationDto1" doesnt exist in the generated json.  Your solution works as expected if it is a List<AddressDto>.

**Comment by justinyoo** [comment]
@obautista Thanks for the issue. Would you please provide me with the `SearchResultDto<AddressDto>` implementation details so that I can have a look?

**Comment by obautista** [comment]
Thanks @justinyoo - 

`public class SearchResultDto<T> where T : class
{
    [JsonProperty("results")]
    public List<T> Results { get; set; }

    [JsonProperty("pagingResult")]
    public PagingResult PagingResult { get; set; }
}`

`public sealed class AddressDto
{
    [JsonIgnore]
    public Guid? Id { get; set; }

    [JsonProperty("documentType")]
    public string DocumentType { get; set; }

    [JsonProperty("deleted")]
    public bool Deleted { get; set; }

    [JsonProperty("versionId")]
    public Guid VersionId { get; set; }
}`

**Comment by justinyoo** [comment]
@obautista Thanks for the class details. But it doesn't seem to be correct.

**Comment by obautista** [comment]
> @obautista Thanks for the class details. But it doesn't seem to be correct.

what isnt correct?

**Comment by justinyoo** [comment]
> `SearchResultDto<AddressDto>`

It looks generic, but your class definition doesn't

**Comment by justinyoo** [comment]
It's merged to the other repo: https://github.com/Azure/azure-functions-openapi-extension
