### ISSUE TITLE
.net Framework 4.6.2 support for v1 Azure Functions?

### ISSUE THREAD

**Issue by filcole** [aliencube/AzureFunctions.Extensions#121]
Is it possible to use .net Framework 4.6.2 with AzureFunctions.Extensions?

**Context**:  I'm trying to create a v1 Azure function that uses the [Dynamics 365/PowerPlatform SDK, which requires .net Framework 4.6.2](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/visual-studio-dot-net-framework), so I have to use at least .net Framework 4.6.2.

I can use Visual Studio 2019 to create a v1 Azure Function, which is initially created with .net Framework 4.6.1.  After installing Aliencube.AzureFunctions.Extensions.OpenApi.Core via nuget I can see the RenderSwaggerUI http functions when running/debugging the Azure function.

As soon as I switch to .net Framework 4.6.2 (or any other version than 4.6.1) I do not see the RenderSwaggerUI http functions anymore. 

Thank you for the very interesting project.

**Comment by justinyoo** [comment]
@filcole Thanks for the issue! Oops, it's a bug. I overlooked that part. In the meantime as a workaround,

1. Install OpenApi.Core package
2. Manually copy over the three files from https://github.com/aliencube/AzureFunctions.Extensions/tree/dev/templates/OpenApiEndpints &ndash; `IOpenApiHttpTriggerContext.cs`, `OpenApiHttpTriggerContext.cs`, and `OpenApiHttpTriggerV1.cs`.
3. Remove `#if NET461` preprocessor within `OpenApiHttpTriggerV1.cs`.

Please have a try and let me know.

**Comment by filcole** [comment]
Hi @justinyoo,

Thanks very much for the quick solution.  The workaround allows the Azure Function to work in .net Framework other than 4.6.1, e.g. 4.6.2

It leads onto the next issue that the latest nuget packages for connecting to Dynamics/PowerPlatform require more recent Newtonsoft.Json than V1 Azure functions provides:

[Microsoft.CrmSdk.XrmTooling.CoreAssembly v9.1.0.51](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/9.1.0.51) require Newtonsoft.Json >= 10.0.3

So trying to access http://localhost:7071/api/swagger.json throws the following error 

`Exception while executing function: RenderSwaggerDocumentInJson -> Method not found: 'Aliencube.AzureFunctions.Extensions.OpenApi.Core.Abstractions.IDocument Aliencube.AzureFunctions.Extensions.OpenApi.Core.Abstractions.IDocument.AddNamingStrategy(Newtonsoft.Json.Serialization.NamingStrategy)'.`

this seems to be the same problem as identified in issue #58.   I'm trying out the suggestions in #58.

**Comment by justinyoo** [comment]
Yeah, unfortunately, if you have to stick with Azure Functions v1 runtime, there's no space I can do for you; other than sticking onto the Newtonsoft.Json version 9.0.1 due to the original runtime issue.

**Comment by justinyoo** [comment]
As I replaced all `NET461` moniker with `NETFRAMEWORK`, it should be fine by now. I'll close this issue. The next release will include this fix.
