### ISSUE TITLE
No error messages given by OpenApi.CLI

### ISSUE THREAD

**Issue by filcole** [aliencube/AzureFunctions.Extensions#122]
Start the azfuncopenapi.exe with missing or invalid parameters and no errors are thrown.

I expect some kind of command line output, e.g. invalid command, or help output.

**Comment by justinyoo** [comment]
@filcole Thanks for the issue. There has been issues around the CLI. I'll fix them sooner than later, including this.

**Comment by asears** [comment]
@justinyoo could you provide a way you currently debug the errors from source?  Experiencing same blank output with no errors or warnings....

**Comment by justinyoo** [comment]
As #123 has been merged, it should be fine by now. I'll close this issue. If you still have the same issue, please feel free to open a new issue.
