### ISSUE TITLE
If CLI path explicitly states .csproj then assembly is not found

### ISSUE THREAD

**Issue by filcole** [aliencube/AzureFunctions.Extensions#124]
Running the following will fail because .csproj is added twice to the URL in `SetProjectPath`

```powershell
# PowerShell Console
.\azfuncopenapi.exe `
    --project  "C:\dev\ABC\FunctionApps.Blaah\FunctionApps.Blaah.csproj" `
    --configuration Debug `
    --target net462 `
    --version v2 `
    --format json `
    --console true
```

**Comment by justinyoo** [comment]
@filcole Thanks for the issue. There has been issues around the CLI. I'll fix them sooner than later, including this.

**Comment by justinyoo** [comment]
Think your PR #125 would fix this issue as well? I'll close this issue for now. If you find it's still an issue, please open a new issue.
