### ISSUE TITLE
CLI releases on github contains identical filenames

### ISSUE THREAD

**Issue by filcole** [aliencube/AzureFunctions.Extensions#126]
Unzipping the CLI files on gives duplicate files, e.g. from here: https://github.com/aliencube/AzureFunctions.Extensions/releases/download/cli-0.8.1/azfuncopenapi-v0.8.1-net461-win-x64.zip

![image](https://user-images.githubusercontent.com/6078398/93031177-b38d7500-f620-11ea-87fd-4b5f30b4c28a.png)

I had to build from source to try out the CLI.

**Comment by justinyoo** [comment]
@filcole Thanks for the issue. There has been issues around the CLI. I'll fix them sooner than later, including this.
