### ISSUE TITLE
Get EnumMember Value

### ISSUE THREAD

**Issue by terra819** [aliencube/AzureFunctions.Extensions#128]
I am trying to use an `enum` that has `EnumMember` values defined instead of `Display` values. Using `StringEnumConverter` generally produces the correct results, but when used with `aliencube.azurefunction.extensions`, it does not. For example, below I want to get the `"Jan"`, `"Feb"`, etc. values from the `enum` into the generated swagger document. Instead I am getting the `"january"`, `"february"`, etc. values. 

![image](https://user-images.githubusercontent.com/1805918/94057897-44e1b180-fdae-11ea-8552-fece348f8bbf.png)

I am using the following configuration: 
```
            var version = OpenApiSpecVersion.OpenApi3_0;
            var extension = OpenApiFormat.Json;

            var filter = new RouteConstraintFilter();
            var acceptor = new OpenApiSchemaAcceptor();
            var namingStrategy = new CamelCaseNamingStrategy();
            var collection = VisitorCollection.CreateInstance();
            var helper = new DocumentHelper(filter, acceptor);
            var document = new Document(helper);
            var openApiInfo = new OpenApiInfo
            {
                Version = "3.0.1",
                Title = "Title",
                Description = "Description",
            };

            var result = await document.InitialiseDocument()
                .AddMetadata(openApiInfo)
                .AddServer(httpRequest, "")
                .AddNamingStrategy(namingStrategy)
                .AddVisitors(collection)
                .Build(Assembly.GetExecutingAssembly())
                .RenderAsync(version, extension)
                .ConfigureAwait(false);
```

How can I get the values inside of the `EnumMember` instead?

**Comment by justinyoo** [comment]
Please follow this https://github.com/Azure/azure-functions-openapi-extension for future update
