### ISSUE TITLE
Documentation stale - OpenApiResponseBody should be OpenApiResponseWithBodyAttribute

### ISSUE THREAD

**Issue by asears** [aliencube/AzureFunctions.Extensions#131]
In <https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi-core.md> the OpenApiResponseBody  example is obsolete- should use OpenApiResponseWithBodyAttribute.

**Comment by justinyoo** [comment]
Thanks! From now on, please have a look at the other repo: https://github.com/Azure/azure-functions-openapi-extension
