### ISSUE TITLE
ReflectionTypeLoadException when running CLI

### ISSUE THREAD

**Issue by sebb3** [aliencube/AzureFunctions.Extensions#132]
When running the CLI I get the following exception:

`Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Aliencube.AzureFunctions.Extensions.OpenApi.DocumentHelper.GetHttpTriggerMethods(Assembly assembly)
   at Aliencube.AzureFunctions.Extensions.OpenApi.Document.Build(Assembly assembly, NamingStrategy namingStrategy)
   at Aliencube.AzureFunctions.Extensions.OpenApi.CLI.Program.Generate(String project, String configuration, String target, OpenApiVersionType version, OpenApiFormatType format, String output, Boolean console)`

I have tried to debug the issue in the CLI, but the only difference is that while debugging it is also unable to load 
`Aliencube.AzureFunctions.Extensions.OpenApi.Core, Version=3.1.1.0, Culture=neutral, PublicKeyToken=null'. `

The Azure Function Project is using netcoreapp3.1

**Comment by sebb3** [comment]
After doing some more investigating, it seems that something in OpenAPI.CLI is referencing v2.1.0 of Microsoft.AspNetCore.Mvc.Core and Microsoft.AspNetCore.Mvc.Abstractions.
I havent been able to figure out where that reference is coming from, but the dlls appear in the CLI:s build folder.

Directly referencing the newer packages in the .csproj file of the CLI fixes the problem. Maybe there's a prettier solution though...

**Comment by justinyoo** [comment]
@sebb3 Thanks for your issue. Would you please let me know which .NET Core SDK version you have installed? You can type `dotnet --list-sdks` to view the list of .NET Core SDK installed on your machine.
