### ISSUE TITLE
Property description added to field?

### ISSUE THREAD

**Issue by theplankmeister** [aliencube/AzureFunctions.Extensions#135]
I can't seem to find documented anywhere a mechanism for parsing a class property description and putting it in the generated swagger definition. I assumed it would just work out-of-the-box by using the "Description" attribute, but no dice. Also tried with a `///<summary>` comment, which doesn't work either. Am I barking up the wrong tree, or is there just no support for property descriptions?

**Comment by justinyoo** [comment]
@theplankmeister Thanks for your issue! I just want to clarify what the "class property description" is about. Do you want to add description to each model definition?

**Comment by justinyoo** [comment]
Related to: https://github.com/Azure/azure-functions-openapi-extension/issues/14

**Comment by justinyoo** [comment]
Please follow https://github.com/Azure/azure-functions-openapi-extension for future update
