### ISSUE TITLE
Updating Authorization Level and Base URL

### ISSUE THREAD

**Issue by disambiguationuk** [aliencube/AzureFunctions.Extensions#136]
Hello, 

I'm trying to update the authorization to anonymous as I'd rather not be exposing my host key as it renders in the Swagger UI page. However, as the Render Swagger UI function is included in the Nuget package I can't find a way to override this. Is there a way to override this in the settings. 

We're also using an Azure API Management Instance and Azure Front Door in front of our API which changes the base url, however on the Swagger UI this is still pointing to the original Azure Function URL, is there a way to override the baseUrl as well?

Thanks,

**Comment by justinyoo** [comment]
@disambiguationuk Thanks for the issue!

> I'm trying to update the authorization to anonymous as I'd rather not be exposing my host key as it renders in the Swagger UI page. However, as the Render Swagger UI function is included in the Nuget package I can't find a way to override this. Is there a way to override this in the settings.

Please refer to #106

> We're also using an Azure API Management Instance and Azure Front Door in front of our API which changes the base url, however on the Swagger UI this is still pointing to the original Azure Function URL, is there a way to override the baseUrl as well?

It's not supported yet. But let me consider whether I can provide a way for the base URL overriding or not.

**Comment by disambiguationuk** [comment]
Cheers @justinyoo, that first one solved that thanks! Couldn't find that one originally as the original question was about source control rather than authorization levels. 

Yeah adjusting the base URL would be pretty important for us, the Azure Function base URL is fairly different from the API Management base URL.

**Comment by hansmbakker** [comment]
Yes! Overriding the base url would be a helpful feature for us as well. Maybe this is something that can be configured in `openapisettings.json`?

**Comment by justinyoo** [comment]
@disambiguationuk @hansmbakker Let me think how it can be done. Thanks for the suggestion!

FYI - I'm thinking of retiring the `openapisettings.json`.

**Comment by justinyoo** [comment]
It's now on the other repo: https://github.com/Azure/azure-functions-openapi-extension
