### ISSUE TITLE
Can we specify our own swagger.json file?

### ISSUE THREAD

**Issue by MRL-00** [aliencube/AzureFunctions.Extensions#138]
There are some generated aspects that are part of this package that are great.
Others that are generated are things I don't want to include within swagger. One of these being the `Code` parameter that you must define if a functions AuthorizationLevel is set to "Function".

Can I define my own swagger.json file that this package can read? That way I could remove the parameter that way.

`"parameters": [
            {
              "name": "code",
              "in": "query",
              "schema": {
                "type": "string"
              }
            }
          ],`

I've tried adding the `json` code to the host.json file however it just takes the header parts (title, description, etc.) but ignores the rest. 

Is this possible?

**Comment by justinyoo** [comment]
The purpose of this extension is to automatically generate the `swagger.json` file.

The next release includes the ability to choose to include/exclude the `code` parameter on the querystring.
