### ISSUE TITLE
OpenApiHttpTriggerContext.cs generates a compiler warning when using C#8 nullable reference types

### ISSUE THREAD

**Issue by paulhickman-a365** [aliencube/AzureFunctions.Extensions#141]
If the C#8 compiler option for nullable reference types is used (````<Nullable>enable</Nullable>```` in the csproj file) in an Azure Functions project, the template OpenApiHttpTriggerContext.cs generates a compiler warning in:

````
        public virtual string GetSwaggerAuthKey(string key = "OpenApi__ApiKey")
        {
            var value = Environment.GetEnvironmentVariable(key);

            return value;
        }
````
As it returns a ````string```` rather than a ````string?```` but it doesn't check and throw an exception if the value is null

**Comment by justinyoo** [comment]
Related to: https://github.com/Azure/azure-functions-openapi-extension/issues/48

@paulhickman-a365 Please try: https://github.com/Azure/azure-functions-openapi-extension

**Comment by justinyoo** [comment]
It's merged on the other repo: https://github.com/Azure/azure-functions-openapi-extension
