### ISSUE TITLE
default "Code" query string on all functions

### ISSUE THREAD

**Issue by lcordidrocl** [aliencube/AzureFunctions.Extensions#142]
Hey, I get this parameter on requests of all my functions, and I don't know where it is coming from, since I am not specifying it with the data annotations:
  "parameters": [
     
      {
          "in": "query",
          "name": "code",
          "type": "string"
      }]

**Comment by justinyoo** [comment]
Please refer to https://github.com/Azure/azure-functions-openapi-extension, where it's implemented
