### ISSUE TITLE
Missing list item type definition

### ISSUE THREAD

**Issue by baltuonis** [aliencube/AzureFunctions.Extensions#143]
Hi, I'm having problems with missing list item type definition. 

Here goes the code:

Function
```
[OpenApiResponseWithBody(HttpStatusCode.OK, MediaTypeNames.Application.Json, typeof(NewDataSet))]
```

NewDataSet:
```
	[XmlRoot]
	public class NewDataSet
	{
		[XmlElement]
		public List<Table> Table { get; } = new List<Table>();
	}
	
	[Serializable]
	public class Table
	{
		[XmlElement]
		public int? nGroupID { get; set; }
		// more....
	}
```

PROBLEM - in the swagger.json output, definitions section we are missing `Table` definition. I can only see `NewDataSet`
```
 "NewDataSet": {
      "type": "object",
      "properties": {
        "Table": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Table"
          }
        }
      }
    }
```

**Comment by justinyoo** [comment]
@baltuonis Thanks for the issue! Can you please try this: https://github.com/Azure/azure-functions-openapi-extension, and let me know? I suspect that your `Table` property has no setter, though.

**Comment by justinyoo** [comment]
I'll close this  issue. If you still face the same problem, please raise it on the other repo: https://github.com/Azure/azure-functions-openapi-extension
