### ISSUE TITLE
authentication settings

### ISSUE THREAD

**Issue by vazeline** [aliencube/AzureFunctions.Extensions#144]
Hi. Is it possible to add authentication settings to configuration in the same way as they exist in .net core libraries:
![image](https://user-images.githubusercontent.com/3456280/110501757-8cb18680-810b-11eb-886d-17d168272906.png)
?

**Comment by justinyoo** [comment]
Related to: https://github.com/Azure/azure-functions-openapi-extension/issues/47#issuecomment-787019497

**Comment by justinyoo** [comment]
It's now merged. Please have a look at the other repo: https://github.com/Azure/azure-functions-openapi-extension
