### ISSUE TITLE
FileUpload support

### ISSUE THREAD

**Issue by Assassinbeast** [aliencube/AzureFunctions.Extensions#146]
Is it possible to POST and upload a binary file?

I tried to use `[OpenApiRequestBody("application/pdf", typeof(byte[]), Required = true)]` to for example upload a pdf file, but it didn't work

For example, when i use Insomnia, i can choose the Body to be a "Binary File" which is what i want
![image](https://user-images.githubusercontent.com/6762656/115234755-b0f48000-a119-11eb-978c-46434068ff1e.png)

I believe its in this OpenAPI docs: https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by justinyoo** [comment]
@Assassinbeast Thank for the issue! It's not supported yet, but it would be great if you have this issue on the other repo, https://github.com/Azure/azure-functions-openapi-extension for further tracking.

**Comment by Assassinbeast** [comment]
> @Assassinbeast Thank for the issue! It's not supported yet, but it would be great if you have this issue on the other repo, https://github.com/Azure/azure-functions-openapi-extension for further tracking.

Oh, thats correct. I will make the issue on that repo.
