### ISSUE TITLE
Support constraints in route 

### ISSUE THREAD

**Issue by SplitThePotJohan** [aliencube/AzureFunctions.Extensions#15]
When generating OpenApi/Swagger for my Azure Functions I noticed that your library does not support routes with constraints in the interpolation.
`Route = "product/{id:int}`

I decorate the method with: 
`[OpenApiParameter("id", In = ParameterLocation.Path, Required = true, Type = typeof(int))]`

But in SwaggerUI the route displays as `.../product/{id:int}` instead of expected `.../product/{id}`.
Also "Try it out" does not replace the path parameter when send ing the request to the function, resulting in a 404 response.

**Comment by justinyoo** [comment]
@SplitThePotJohan Thanks for the issue! Would you be able to share codes, if you don't mind? I'm not sure I understood this issue.

**Comment by SplitThePotJohan** [comment]
I cant share my code right now, but I can walk you through it.

Create a function like this: (note: simplified method body)
```
        [FunctionName("GetProduct")]
        [OpenApiOperation("get", "product")]
        [OpenApiParameter("category", In = ParameterLocation.Path, Required = true, Type = typeof(string))]
        [OpenApiParameter("id", In = ParameterLocation.Path, Required = true, Type = typeof(int))]
        [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(object))]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "{category:regex(^[A-Z]{{3,}}$)}/product/{id:int}")] HttpRequest req,
            string category,
            int id,
            ILogger log)
        {
			return new JsonResult(new { category, id });
	}
```
Then I used your sample to setup OpenApi/Swagger.
E.g. `RenderOpenApiDocument`-method and `RenderSwaggerUI`-method

When I run the SwaggerUI, the route displays as `GET /api/{category:regex(^[A-Z]{{3,}}$)}/product/{id:int}` and a similar route using for instance Swashbuckle (not an Azure Fn api method) would display `GET /api/{category}/product/{id}`.

I can live with that, it doesnt matter how the UI looks, but when I use "Try it out" I see that the values I submitted are not replaced in the actual call.

```
CURL
curl -X GET "http://localhost:7071/api/{category:regex(^[A-Z]{{3,}}$)}/product/{id:int}" -H "accept: application/json"

Request URL
http://localhost:7071/api/{category:regex(^[A-Z]{{3,}}$)}/product/{id:int}
```
And this requested url is not the intended (and results in a 404 error, of course)

Hope this explaination helps you understand my issue.

**Comment by justinyoo** [comment]
@SplitThePotJohan Thanks for the elaboration! Let me take some time to have a look and get back to you. Unfortunately, I've got full capacity for other personal priorities, I'm afraid I can't take this sooner.

**Comment by justinyoo** [comment]
@SplitThePotJohan was able to reproduce this on my side.

Basically, for this defect, if the UI replaces:

    {category:regex(^[A-Z]{{3,}}$)}/product/{id:int}

with

    {category}/product/{id}

it would solve this issue. Do you think it's OK?

**Comment by SplitThePotJohan** [comment]
@justinyoo yes, I think that would solve the issue.
I suppose this change will enable the functionality for "Try it out" to work as expected?
And of course the same fix should be applied for the generation of e.g `swagger.json`

**Comment by justinyoo** [comment]
@SplitThePotJohan Yes, that's the plan. I've made some changes for this, and it's staying at the `feature/15-route-constraint` branch. You can try it, if you like. It needs more polish-up, though.

**Comment by justinyoo** [comment]
Fixed
