### ISSUE TITLE
DocumentHelper.cs - missing "Description" in swagger output

### ISSUE THREAD

**Issue by jassent** [aliencube/AzureFunctions.Extensions#16]
Your library is great! Thank you for putting it together. This function is missing Description = op.Description which causes a validation error when importing the swagger.json into Azure to create a Logic App Custom Connector. This is in the file DocumentHelper.cs around line 90.
```csharp
 var operation = new OpenApiOperation()
                                {
                                    OperationId = string.IsNullOrWhiteSpace(op.OperationId) ? $"{function.Name}_{verb}" : op.OperationId,
                                    Tags = op.Tags.Select(p => new OpenApiTag() { Name = p }).ToList(),
                                    Summary = op.Summary,
                                    Description = op.Description
                                };
```

**Comment by justinyoo** [comment]
@jtawil777 Thanks for piling this issue! I'll have a look. This should have been included.
