### ISSUE TITLE
Swagger = how to get the value in path product/{id}/table/name

### ISSUE THREAD

**Issue by Hussamalsh** [aliencube/AzureFunctions.Extensions#17]
Hi 
I am trying to get the value from the path product/{id}/table/name in swagger.

Code:
[OpenApiParameter("{id}", In = ParameterLocation.Path, Required = true, Type = typeof(string), Description = "product id", Visibility = OpenApiVisibilityType.Advanced)]

**Comment by SplitThePotJohan** [comment]
@Hussamalsh I think you should omit the curly brackets.
Like this:
```
[OpenApiParameter("id", In = ParameterLocation.Path, Required = true, Type = typeof(string), Description = "product id", Visibility = OpenApiVisibilityType.Advanced)]
```

**Comment by Hussamalsh** [comment]
> @Hussamalsh I think you should omit the curly brackets.
> Like this:
> 
> ```
> [OpenApiParameter("id", In = ParameterLocation.Path, Required = true, Type = typeof(string), Description = "product id", Visibility = OpenApiVisibilityType.Advanced)]
> ```

i did that before doesn't work, but tried again and now it's works :)
