### ISSUE TITLE
Annotate properties in request models

### ISSUE THREAD

**Issue by spaelling** [aliencube/AzureFunctions.Extensions#18]
Is it possible to annotate properties in the request models to ex. describe if the property is mandatory or not. I think this is already in the OpenAPI spec.

**Comment by justinyoo** [comment]
@spaelling In general, yes, if you use `JsonProperty(...)` from Json.NET. Is that what you're looking for, or something else? If you want to explicitly show them, I don't think it's implemented yet, as this is optional from the spec. However, it's in our backlog #4 .

**Comment by spaelling** [comment]
Thanks, I will try it out and let you know if that was my meaning. It looks promising.

**Comment by spaelling** [comment]
That did not quite do what I was hoping for. We will be awaiting #4
