### ISSUE TITLE
Does this expose itself to Logic Apps?

### ISSUE THREAD

**Issue by VictorioBerra** [aliencube/AzureFunctions.Extensions#22]
EDIT: Removed the questions that are only related to V1.

Will this automatically expose itself to Logic Apps? Maybe the endpoint in the function needs to have a special name?

**Comment by justinyoo** [comment]
@VictorioBerra Thanks for the question! It's already answered by itself, though.

> Will this automatically expose itself to Logic Apps? Maybe the endpoint in the function needs to have a special name?

That's something both Azure Functions team and Logic Apps team work together, as this more towards their architectural decision. If you want to expose Azure Functions Swagger, you better consider a custom connector. That works.

**Comment by VictorioBerra** [comment]
Gotcha. So it sounds like Logic Apps **wont** pick up the document and start assisting me with suggestions about my functions response schema.
