### ISSUE TITLE
Section SecurityRequirements is missing

### ISSUE THREAD

**Issue by tjgalama** [aliencube/AzureFunctions.Extensions#27]
When added security scheme's SwaggerUI also requires a `security` section that references to the security scheme like:
``` json
"securityDefinitions": {
	"authKey": {
		"type": "apiKey",
		"name": "x-functions-key",
		"in": "header"
	}
},
/* missing : */
"security": [
        {
            "authKey": []
        }
}
```
As a result the entered authentication is NOT applied when executing the call's. (in this case; the x-function-key missing in the header of the request). 
The fix is easy add the following to the Document.Build(..)
``` CSharp
 if (_document.Components.SecuritySchemes != null ||
    _document.Components.SecuritySchemes.IsEmpty())
{
    var securityRequirement = new OpenApiSecurityRequirement();
    foreach (var securitySchemeId in _document.Components.SecuritySchemes.Keys)
    {
        var key = new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference
            {
                Id = securitySchemeId,
                Type = ReferenceType.SecurityScheme
            }
        };
        securityRequirement.Add(key, new string[0]);
    }
    _document.SecurityRequirements.Add(securityRequirement);
}
```

**Comment by justinyoo** [comment]
@tjgalama Thanks for the issue! I'll have a look.

**Comment by tjgalama** [comment]
Ahum, Although it would be nice to have _document.SecurityRequirements somehow extendable, I noticed that my fix to add all scheme's by default, is not always preferred. 
In my case it was even better to add the referenced security scheme's to the Security property of the individual OpenApiOperation objects.

**Comment by justinyoo** [comment]
@tjgalama The security scheme appears on both operation level and root level.

If I understand your issue correctly, originally you prefer putting the security scheme at the root level, but then suggested to put it on the operation level. Is that correct?

And I think, if we implement, this scheme should appear on both levels &ndash; one for host key and the other for function key. How does this sound?

**Comment by Pharylon** [comment]
I'm not sure how you'd put it at the operation level, it's not spelled out in the docs. I've been banging my head at this issue all day, and the fix from @tjgalama saved me a few more hours of work. Thanks!

**Comment by mehdi-ichka** [comment]
I needed to add 'x-functions-key' in the root level @tjgalama 's solution solves my problem and saves my day. It would be more convenient if the Document class is extensible.

**Comment by justinyoo** [comment]
It's implemented at https://github.com/Azure/azure-functions-openapi-extension Please check this repo for future update
