### ISSUE TITLE
Add a minimal sample

### ISSUE THREAD

**Issue by seertenedos** [aliencube/AzureFunctions.Extensions#31]
Your original blog post made things mostly simple but the samples you currently have rely on you needing DI and another project that is not a nuget just to add swagger. It seems overly complex just to add open API and swagger compared to the initial version. 

I would have thought this could all be done with a single sample class that contains all needed functions and some nuget references. Bonus would be of a single nuget could add the class to the project and the references to the other nugets needed.

**Comment by hf-kklein** [comment]
I second this. Using the instructions in [openapi.md](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md) seems overly complex to start with.

**Comment by justinyoo** [comment]
This is related to #6

**Comment by justinyoo** [comment]
@seertenedos Thanks for your comment! I'm currently working on this at #6 .

**Comment by justinyoo** [comment]
It's now available from [1.8.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.8.0)
