### ISSUE TITLE
Sample for doing auth for functions with "User" auth

### ISSUE THREAD

**Issue by seertenedos** [aliencube/AzureFunctions.Extensions#32]
It would be great to see a sample of how to do user auth using Azure AD for example. To do this currently I think you need to extend the formatter that is passed into the document but I am still playing to work it all out. It would be great if there was an easy way to configure it.

**Comment by justinyoo** [comment]
@seertenedos Would you be able to elaborate, please? My limited imagination doesn't allow me to look further.

**Comment by aleccaputo** [comment]
@justinyoo @seertenedos 
Not sure if this is exactly what you're referring to, but it would be nice to be able to define a different OpenApiSecurityScheme on the root of the Document other than "x-functions-key". Supporting Bearer tokens, for example.

**Comment by seertenedos** [comment]
Sorry for the slow reply. I just worked out how user based Auth works and
instead it is all about using anonymous on the function but changing a
setting in Azure to force auth. If you set it to user it fails even if they
are authenticated.

Due to this you can close this as not needed.

**Comment by justinyoo** [comment]
@seertenedos Thanks for the clarification!
