### ISSUE TITLE
Give Ability to Configure Security Scheme

### ISSUE THREAD

**Issue by aleccaputo** [aliencube/AzureFunctions.Extensions#35]
It would be nice to be able to define a different OpenApiSecurityScheme on the root of the DocumentHelper other than "x-functions-key". 
This would add support for custom bearer auth, for example.
See DocumentHelper.cs line 172

**Comment by justinyoo** [comment]
@aleccaputo Thanks for the issue raised. I'll have a look whether this needs to be in our scope or not.

**Comment by richardhauer** [comment]
An update for this would be great.  It's a bit harsh to dictate that all APIs are using the authentication scheme you nominate.  Azure Function Keys are not the only authentication system available to Azure Functions - they're not even the preferred system!

See [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#authorization-keys](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#authorization-keys)

**Comment by rodrigoramirez93** [comment]
Is there any hack around this to at least make it work? btw great work guys

**Comment by justinyoo** [comment]
Please refer to https://github.com/Azure/azure-functions-openapi-extension, where it's implemented
