### ISSUE TITLE
Generated error: operationId is repeated

### ISSUE THREAD

**Issue by DarinMacRae** [aliencube/AzureFunctions.Extensions#38]
This may or may not be a bug but since I cannot figure out if I am doing anything wrong I thought I'd create an issue so a solution can be shared.

I have a very simple app with two routes.
 - foo
 - foo/{id}

Why do I get this error generated in the Swagger UI?

```
{
  "messages": [
    "attribute paths.'/foo/{id}'(get).operationId is repeated"
  ]
}
```

**Comment by hf-kklein** [comment]
Could you please post the function signatures and attributes, too?

**Comment by justinyoo** [comment]
@DarinMacRae Is it the same issue as #15 ?

**Comment by DarinMacRae** [comment]
@justinyoo I don't think so. I'm not using any route constraints. The example really is as simple as I posted. Since I opened the issue I've seen this issue again on multiple projects. I've just been ignoring it since the UI still generates. It's just annoying that it complains and I don't know why.

**Comment by DarinMacRae** [comment]
The reason I was seeing this issue is because I was following the examples too closely without reading the source carefully enough. This is no longer an issue for me.
