### ISSUE TITLE
New JObject support is generating Swagger Error

### ISSUE THREAD

**Issue by glennular** [aliencube/AzureFunctions.Extensions#39]
I have pulled the latest code and see the Error iIincluded below, when expanding the method.

Related to #29 

```
Errors
Resolver error at paths./samples/{id}/categories/{category}.get.responses.404.schema.$ref
Could not resolve reference: Could not resolve pointer: /definitions/JObject does not exist in document
Resolver error at paths./samples/{id}/categories/{category}.get.responses.500.schema.$ref
Could not resolve reference: Could not resolve pointer: /definitions/Dictionary`2 does not exist in document
```

![image](https://user-images.githubusercontent.com/2328657/58680541-c72ea280-832d-11e9-9ea3-a5d80f3199a0.png)

**Comment by justinyoo** [comment]
@glennular I just pulled the latest code as like fresh install, and ran the sample app that contains both `JObject` and `Dictionary<string, int>` as the response payload. But it works fine to me.

![image](https://user-images.githubusercontent.com/1538528/58683246-17057c00-83b7-11e9-8b21-ff5a0c41b628.png)

Would you double check whether you have the latest commit from the `dev` branch?

**Comment by justinyoo** [comment]
Ahh, I got the error. I should remove both response payload as this is not acceptable, as mentioned in #29

**Comment by justinyoo** [comment]
@glennular Commented out those two response payload definition lines.
