### ISSUE TITLE
Add missing Open API specs

### ISSUE THREAD

**Issue by justinyoo** [aliencube/AzureFunctions.Extensions#4]

**Comment by bartdk-be** [comment]
* small bump
Any plans on adding the missing items to your nuget package ?

**Comment by justinyoo** [comment]
@bartdk-be I haven't decided which one to do first. Do you have anything in mind to add first?

**Comment by justinyoo** [comment]
As mentioned at #18, request/response payload "required" property needs to be added first.

**Comment by ghost** [comment]
Perhaps some of the basic [C# DataAnnotations](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations?view=netframework-4.8) that have a natural equivalent in OpenAPI would be good candidates?  I.e.:
- RequiredAttribute (as mentioned)
- MaxLengthAttribute
- MinLengthAttribute
- DataTypeAttribute
- RangeAttribute

I'm new to OpenAPI and assume these are natural.
