### ISSUE TITLE
An option to provide sample responses would be great

### ISSUE THREAD

**Issue by richardhauer** [aliencube/AzureFunctions.Extensions#43]
Looks like the system auto-generates response samples but for a commercial system we are happy to supply meaningful samples.

**Comment by justinyoo** [comment]
@richardhauer Thanks for the suggestion! I'll have a look and start working based on priority.

**Comment by justinyoo** [comment]
Please refer to https://github.com/Azure/azure-functions-openapi-extension/issues/37 for future WIP

**Comment by justinyoo** [comment]
@richardhauer Finally it's sorted out and merged! Please have a look at: https://github.com/Azure/azure-functions-openapi-extension/pull/95

**Comment by justinyoo** [comment]
Thanks for your waiting!
