### ISSUE TITLE
Merging dev to master and cutting new nuget

### ISSUE THREAD

**Issue by otryshko** [aliencube/AzureFunctions.Extensions#44]
Hello,

There is a bug which got fixed in dev but haven't made it to master (and nuget) yet - when (if?) is dev going to be merged to master and new nuget cut? Or should I fork the repo, merge/publish a different nuget?

**Comment by justinyoo** [comment]
@otryshko Thanks for your patience! A new release (1.5.4) has been released to [NuGet](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.5.4).
