### ISSUE TITLE
Option to not include "function code" as default parameter 

### ISSUE THREAD

**Issue by magnarw** [aliencube/AzureFunctions.Extensions#46]
The current implementation of DocumentHelper includes "function code" as a parameter as long as the trigger does not have anonymous auth level.
I would be great if clients of the DocumentHelper could override this behavior as the function code is unwanted as part of the api doc in certain cases.  We use this library on functions that we publish directly to api management were we have other authentication  polices in place and does not expect the clients to know the function code

**Comment by otsomkalov** [comment]
Temporary solution: create class inherited from DocumentHelper
```
public class CustomDocumentHelper : DocumentHelper, IDocumentHelper
    {
        public CustomDocumentHelper(RouteConstraintFilter filter) : base(filter)
        {
        }

        public new List<OpenApiParameter> GetOpenApiParameters(
            MethodInfo element,
            HttpTriggerAttribute trigger)
        {
            var list = element.GetCustomAttributes<OpenApiParameterAttribute>(false)
                .Select(p => p.ToOpenApiParameter())
                .ToList();

            return list;
        }
    }
````
and then add to services: 
`                .AddTransient<IDocumentHelper, CustomDocumentHelper>()
`

**Comment by bseng** [comment]
Hi I tried the temporary solution but it did not work for version 3.0.0.

Can we introduce an environment variable "Openapi__CodeQuery" to turn off when needed?

**Comment by justinyoo** [comment]
@bseng Let me have a look.

**Comment by MRL-00** [comment]
@justinyoo is there any update on this? I would like to use the Authorize button inside the Swagger UI instead of needing to put the API code inside the default Code Parameter. It would be great if we could have a way to remove this parameter. 
Refer to the image below.
![image](https://user-images.githubusercontent.com/2846782/98868868-b0eeb500-24d5-11eb-8b29-60f22bfc0bb1.png)

**Comment by justinyoo** [comment]
Please refer to this repo: https://github.com/Azure/azure-functions-openapi-extension, where this feature has been implemented
