### ISSUE TITLE
Add support to multiple response type (support oneof, anyof, allof)

### ISSUE THREAD

**Issue by otsomkalov** [aliencube/AzureFunctions.Extensions#47]
Swagger: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
Example: let us have two response definitons:
```
        public class CatResponse : AnimalResponse
        {
            public int MaxSpeed { get; set; }
        }

        public class BirdResponse : AnimalResponse
        {
            public int MaxFlightAttitude { get; set; }
        }
```
allow to do something like below where we can allow several types for response
```
[OpenApiResponseBody(
            HttpStatusCode.OK,
            "application/json",
            new[] {typeof(IList<CatResponse>), typeof(IList<BirdResponse>)},
            Description = "Return list of animals")]
```

**Comment by justinyoo** [comment]
@otsomkalov Thanks for the issue! At this time, I have no plan to implement this, but certainly, it will be included.

**Comment by AccsoSG** [comment]
@justinyoo are there any updates yet? That would be a great feature.
