### ISSUE TITLE
Generic Types with simple types as subtype generate errors on swagger UI

### ISSUE THREAD

**Issue by Stutben** [aliencube/AzureFunctions.Extensions#48]
Hi,

really appreciate your work!
I think I found an issue when you use a generic type as in ResponseBody/RequestBody attribute.
I used a generic type with an Integer or String as subtype and I got the following error when I click on the corresponding schema on the swagger UI

![SchemaMissingError](https://user-images.githubusercontent.com/23017187/61055047-f803fc00-a3f0-11e9-976f-71a08f44ae12.PNG)

**Comment by justinyoo** [comment]
@Stutben Thanks for the issue! Can you provide me with your request/response body class structure? I've been suffering this generic type.

**Comment by Dan-Williams93** [comment]
@justinyoo i am also having this issue with the latest release. I have provided a simple example of how i am trying to use the ResponseBody attribute on #40

**Comment by justinyoo** [comment]
@Stutben @Dan-Williams93 This now has been fixed on [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0).
