### ISSUE TITLE
Support of multiple return types

### ISSUE THREAD

**Issue by a-z-hub** [aliencube/AzureFunctions.Extensions#51]
On action with ability to return multiple results:
`
[OpenApiResponseBody(statusCode: ..., contentType: "...", bodyType: typeof(DataResponse))]
[OpenApiResponseBody(statusCode: ..., contentType: "...", bodyType: typeof(ErrorResponse))]
[OpenApiResponseBody(statusCode: ..., contentType: "...", bodyType: typeof(string))]
[OpenApiResponseBody(statusCode: ..., contentType: "...", bodyType: typeof(string))]
`

I got error:
`
An unhandled host error has occurred.
[7/25/2019 10:52:51 AM] Newtonsoft.Json: Unable to cast object of type 'App.Functions.Models.ErrorResponse' to type 'System.Collections.IEnumerable'.`

My functions:
`
public async Task<IActionResult> GetAsync(
[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "data")] HttpRequest request)
{
...
    if (!validation.IsValid)
    {
        return new BadRequestObjectResult(new ErrorResponse(validation.Errors));
    }
...
        return new OkObjectResult(result);
    }
`

**Comment by justinyoo** [comment]
@ahryshchanka Thanks for the issue! Let me have a look. It seems that your `ErrorResponse` is converted to `IEnumerable`. I'm scratching my head why it's happening.

Can you elaborate with more details?

**Comment by justinyoo** [comment]
As I haven't heard of anything, I'll close this ticket now. If you have more details to share, please re-open this issue.
