### ISSUE TITLE
JsonProperty attribute ignored for model

### ISSUE THREAD

**Issue by a-z-hub** [aliencube/AzureFunctions.Extensions#52]
swagger.json file contains names of properties, not value in JsonProperty  attribute and swagger ui contains "invalid" and send it too.

![image](https://user-images.githubusercontent.com/4180472/61874203-75029b80-aef0-11e9-8af6-5e1ab9c406f1.png)

![image](https://user-images.githubusercontent.com/4180472/61873964-d0805980-aeef-11e9-90a5-07ea6325c9a2.png)

**Comment by Bpflugrad** [comment]
I also ran into this problem.  Here's the solution I found:
In `Aliencube.AzureFunctions.Extensions.OpenApi.Extensions.OpenApiSchemaExtensions.ToOpenApiSchema(Type, NamingStrategy, OpenApiSchemaVisibilityAttribute)` replace `property.Name` on lines 115, 137, 150, 155, and 160 with `propertyName`, which was already defined on line 110.

This fixed it for me in my local copy.

**Comment by Bpflugrad** [comment]
I submitted PR #53 to hopefully get this fix merged.

**Comment by justinyoo** [comment]
@ahryshchanka Thanks for the issue raised! AS @Bpflugrad mentioned, his PR has been merged.
