### ISSUE TITLE
Enum ToDataType method overly restrictive

### ISSUE THREAD

**Issue by brphelps** [aliencube/AzureFunctions.Extensions#54]
It looks like the ToDataType method in EnumExtensions prevents things like byte-backed Enums from working in generated swagger doc. Is there a design reason from this, or could it be added to the number switch cases?

**Comment by justinyoo** [comment]
@brphelps Thanks for the issue! From [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0), the enum now supports `short`, `int` and `long`.
