### ISSUE TITLE
Auto-add functions to expose swagger/doc

### ISSUE THREAD

**Issue by wobba** [aliencube/AzureFunctions.Extensions#6]
It would be very useful when adding the nuget package `Aliencube.AzureFunctions.Extensions.OpenApi` that it automatically added functions for `RenderOpenApiDocument` and `RenderSwaggerUI`.

This would make it a lot easier to add this to existing projects instead of cloning the sample functions and merging with existing code.

* Add nuget
* Annotate
* Run
* :-)

**Comment by justinyoo** [comment]
@wobba Thanks for the suggestion! As I mentioned in my blog post, it’s really a good idea. I’ll find a way to hook this.

**Comment by spaelling** [comment]
Would also be nice to get some scaffolding from what can be found in [FunctionAppCommon](https://github.com/aliencube/AzureFunctions.Extensions/tree/dev/src/Aliencube.AzureFunctions.FunctionAppCommon)
Also I see no issue in including some samples, people can always delete the samples. It just helps getting up and running faster with this.

**Comment by justinyoo** [comment]
Also consider this: https://devkimchi.com/2019/02/02/introducing-swagger-ui-on-azure-functions/#comment-4414226775

**Comment by 1TheMuffinMan** [comment]
I agree with this request. It took me a considerable amount of time to get this working in my project. I had to pull down the samples and spend another hour figuring out why it worked and mine didn't. Appreciate all of your hard work thus far 👍

**Comment by justinyoo** [comment]
@1TheMuffinMan Thanks! I've been working on it for a while. In the meantime, can you try this approach. It installs the boilerplate code so that you don't have to worry about that part

https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md#option-1-install-open-api-boilerplate-templates

Ultimately, I'll make the package that you won't need to install the boilerplate codes at all.

**Comment by justinyoo** [comment]
It's now available from [1.8.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.8.0)
