### ISSUE TITLE
An item with the same key has already been added. Key: ICollection

### ISSUE THREAD

**Issue by eugenpodaru** [aliencube/AzureFunctions.Extensions#61]
The document generation fails with the following exception:

> An item with the same key has already been added. Key: ICollection.

I have traced this to the DocumentHelper class, GetOpenApiSchemas method.

When creating the dictionary of schemas, it uses as key either the type name or the underlying type name in case it's a generic type. This means that if you are returning ICollection<ClassA> and ICollection<ClassB> from 2 of your functions, they will both resolve to the ICollection key, and it will fail with the above exception.

Also, if you are returning NamespaceA.MyClass and NamespaceB.MyClass from 2 of your functions, they will both resolve to the MyClass key, and it will fail with the above exception.

The way Swashbuckle.AspNetCore.Swagger solves this, is by allowing you to specify a function to  generate custom schema ids, something like this:
```
services.AddSwaggerGen(options =>
{
    options.CustomSchemaIds(x => x.FullName);
});
```

**Comment by justinyoo** [comment]
@eugenpodaru Thanks for the issue! This has been fixed on [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0)
