### ISSUE TITLE
AppSettings class used on docs page not available

### ISSUE THREAD

**Issue by Matthewsre** [aliencube/AzureFunctions.Extensions#63]
On the docs page for: Aliencube.AzureFunctions.Extensions.OpenApi

unable to find any namespaces that include the reference to AppSettings:

`var settings = new AppSettings();`

All other references are resolved. Is there another nuget package to include?

**Comment by hf-kklein** [comment]
> Is there another nuget package to include?

[Aliencube.AzureFunctions.Extensions.Configuration.AppSettings](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.Configuration.AppSettings/1.1.0?_src=template).

@Matthewsre would you like to create a pull for [openapi.md](https://github.com/aliencube/AzureFunctions.Extensions/blob/2a088fb3717a644ffe203bf012af2da96f29adfc/docs/openapi.md) request for this issue

**Comment by senften** [comment]
After installing Aliencube.AzureFunctions.Extensions.Configuration.AppSettings 1.1.0 AppSettings is not resolved.

**Comment by Matthewsre** [comment]
@hf-kklein, Tried adding that and still not resolving as reported by @senften .

Since AppSettings doesn't appear to be included in the latest NuGet packages I just added the following to my project to move past this issue:

```
    public class AppSettings : OpenApiAppSettingsBase
    {
        public AppSettings() : base() {}
    }
```

Everything is working correctly with this work around, but not sure why this class isn't included.

Verified manual reference as suggested should not be needed:

![image](https://user-images.githubusercontent.com/2955659/65569805-ae1cb380-df13-11e9-87a1-f8f545b21d4e.png)

![image](https://user-images.githubusercontent.com/2955659/65569874-eae8aa80-df13-11e9-9c39-1b14edfb4ac7.png)

**Comment by androidand** [comment]
I stumbled over the same issue trying to add openAPI to my v2 function.

**Comment by shelbaz** [comment]
@Matthewsre Thanks !

**Comment by santhosh-caw** [comment]
I too have the same issue, If any one solved this please write to me.

**Comment by justinyoo** [comment]
Oops my bad. [`AppSettings`](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/src/Aliencube.AzureFunctions.FunctionAppCommon/Configurations/AppSettings.cs) class stated in the [openapi.md](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md) SHOULD inherit [`OpenApiAppSettingsBase`](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/src/Aliencube.AzureFunctions.Extensions.OpenApi/Configurations/OpenApiAppSettingsBase.cs). I'll update the doc.

**Comment by justinyoo** [comment]
From `1.7.0`, there is no dependency on `AppSettings`. Please following the revised document, https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md
