### ISSUE TITLE
Sbyte datatype in model causes swagger rendering to fail

### ISSUE THREAD

**Issue by rkbalu** [aliencube/AzureFunctions.Extensions#64]
First of all, thanks for this nuget. This helps certainly to document the Azure function api's.

When i try it out found that if the model has the datatype as SByte, it causes Swagger rendering to fail with the below error, bool works.

Are there any restriction if so why?

any help on this one would be really helpful.

![image](https://user-images.githubusercontent.com/33522349/72528123-38da4300-3862-11ea-9d91-35b7d6679d39.png)

**Model Definition:**
public class Bet
{
        [JsonProperty("id")]
        public sbyte Id { get; set; }
}

**Comment by justinyoo** [comment]
@rkbalu Thanks for the issue! it doesn't support `sbyte`. Can you try `short` instead?
