### ISSUE TITLE
.NET Core v3 and Json.NET

### ISSUE THREAD

**Issue by OskarNet** [aliencube/AzureFunctions.Extensions#65]
Hi

Was wondering if you are going to support the new built-in JSON support?  The issue is that Json.NET is not working with Azure Functions after version 3.0 of .NET Core so types like enums will not be correctly specified in the Swagger document.

**Comment by justinyoo** [comment]
@OskarNet As Azure Functions v3 runtime still supports Json.NET, I don't have a plan to support the other one, `System.Text.Json` yet.
