### ISSUE TITLE
How to add Examples Value to Request & Response Model in Swagger UI

### ISSUE THREAD

**Issue by tkwin** [aliencube/AzureFunctions.Extensions#66]
![image](https://user-images.githubusercontent.com/6246461/73836354-71f04c80-483d-11ea-9487-59beefaf53fb.png)
I can't find solutions using this extension to bind default example values for Request & Response Model for Http Trigger on Azure Function 2.x.  Please let me know if there are alternative ways to solve with it.

**Comment by justinyoo** [comment]
Hi, @tkwin It's not been supported yet.

**Comment by justinyoo** [comment]
Related to #43

**Comment by justinyoo** [comment]
Please refer to https://github.com/Azure/azure-functions-openapi-extension/issues/37 for future WIP

**Comment by justinyoo** [comment]
@tkwin Finally it's sorted out and merged! Please have a look at: https://github.com/Azure/azure-functions-openapi-extension/pull/95

**Comment by justinyoo** [comment]
Thanks for your waiting!
