### ISSUE TITLE
Support for V3

### ISSUE THREAD

**Issue by AlbertoDePena** [aliencube/AzureFunctions.Extensions#69]
I just came across on this project! awesome, awesome job!!!
Will there be support for Azure Functions V3? I would like to contribute =)

**Comment by KrzychuR** [comment]
I'm using it with V3. I don't see any big issues except well know already covered by some PR waiting for approve :) Maybe mine case is too simple ;)

**Comment by justinyoo** [comment]
@AlbertoDePena The current release supports V3 runtime. I've added a sample function app targeting V3.
