### ISSUE TITLE
Support for formdata (upload og files)

### ISSUE THREAD

**Issue by Svalhansen** [aliencube/AzureFunctions.Extensions#71]
I would like to be able to setup form data upload of muliple files which seems impossible as of the current body signature.

**Comment by justinyoo** [comment]
@Svalhansen It's not implemented yet. I have no plan to implement this feature, as of today. However, it will be implemented as it's in the spec. I'll keep open this issue.

**Comment by webdes03** [comment]
Any ETA on this? I don't need to upload multiple files, just a single one with application/octet-stream, but nothing I do seems to work.

**Comment by justinyoo** [comment]
Please follow https://github.com/Azure/azure-functions-openapi-extension/issues/18 for future WIP
