### ISSUE TITLE
.Net Core 3.1 is not supported

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [aliencube/AzureFunctions.Extensions#72]
Importing the 4 Nuget packages into my dotNet Core 3.1 results in the below message.

> Warning	NU1701	Package 'Aliencube.AzureFunctions.Extensions.Configuration.Json 2.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

		

It appears that Aliencube.AzureFunctions.Extensions.Configuration.Json does not support dotNet Core.

**Comment by justinyoo** [comment]
@PhilipAnthonyMurray Hi, there. The package, `Aliencube.AzureFunctions.Extensions.Configuration.Json` is for Azure Functions v1 that only supports .NET Framework. If you're targeting .NET Core 3.1, it shouldn't be included.
