### ISSUE TITLE
Working examples

### ISSUE THREAD

**Issue by spaelling** [aliencube/AzureFunctions.Extensions#8]
I made a comment on your [blogpost](https://devkimchi.com/2019/02/02/introducing-swagger-ui-on-azure-functions/) - not there anymore, perhaps you need to approve it first.

Just incase you miss it I will repeat it here.

I was unable to follow the instructions in this guide, ex. ```var settings = new AppSettings();``` is that coming from the nuget package?

I then had a look at the Github project and while I was doing so a commit hit and changed things around. I cloned the repository and build ```Aliencube.AzureFunctions.FunctionAppCommon``` and ```Aliencube.AzureFunctions.Extensions.OpenApi``` and included both in my own project. Everything complies just fine if using the <a href="https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/src/Aliencube.AzureFunctions.FunctionAppV2/OpenApiHttpTrigger.cs">example</a> from Github. I dot get an error when running the app
```
[2/11/2019 2:17:44 PM] Executed 'RenderSwaggerUI' (Failed, Id=65fbf008-1925-40f3-98b8-a70169927f8a)
[2/11/2019 2:17:44 PM] System.Private.CoreLib: Exception while executing function: RenderSwaggerUI. Aliencube.AzureFunctions.FunctionAppCommon: Method not found: 'System.Threading.Tasks.Task`1<Aliencube.AzureFunctions.Extensions.OpenApi.Abstractions.ISwaggerUI> Aliencube.AzureFunctions.Extensions.OpenApi.Abstractions.ISwaggerUI.BuildAsync()'.
```
If using the example from this post I get a compiler error at ```.BuildAsync(typeof(SwaggerUI).Assembly)``` as BuildAsync does not take any input. I can get it to compile if I do ```.BuildAsync().GetAwaiter().GetResult()``` but then I am back to the error from before.

Does the examples work with the latest nuget package, or am I missing something?

Looking forward to getting this to work, great work!

**Comment by justinyoo** [comment]
@spaelling  Thanks for raising the issue. You got the point!

1. I recently refactored the sample code for both V1 and V2 to be reused. It has brought about some misalignment with the document. I’ll chase that up as soon as possible.

1. The `BuildAsync()` method has also been updated during the activity above, but this hasn’t been released yet. I’m going to release this with #7 . In a nutshell, current release has the parameter of `Aeembly`, but the next release will be removed.

1. The `AppSettings` class comes from each function instance, not the NuGet package. It’s basically deserialising the App Settings environment variables. But I might need to revise this part whether it’s a good idea to include in the package or not.

Hope this helps.

**Comment by spaelling** [comment]
Ok, so the example in [Aliencube.AzureFunctions.FunctionAppV2](https://github.com/aliencube/AzureFunctions.Extensions/tree/dev/src/Aliencube.AzureFunctions.FunctionAppV2) does not work yet? When copying that code I get the error

```
[2/12/2019 7:54:30 AM] Executed 'RenderSwaggerUI' (Failed, Id=81e4696d-ebc2-42f0-b975-ae5677e90760)
[2/12/2019 7:54:30 AM] System.Private.CoreLib: Exception while executing function: RenderSwaggerUI. Aliencube.AzureFunctions.FunctionAppCommon: Method not found: 'System.Threading.Tasks.Task`1<Aliencube.AzureFunctions.Extensions.OpenApi.Abstractions.ISwaggerUI> Aliencube.AzureFunctions.Extensions.OpenApi.Abstractions.ISwaggerUI.BuildAsync()'.
```

**Comment by justinyoo** [comment]
Can you check out the `master` and run if it’s working?

**Comment by spaelling** [comment]
> Can you check out the `master` and run if it’s working?

Sort of. If I compile `Aliencube.AzureFunctions.FunctionAppCommon` and `Aliencube.AzureFunctions.Extensions.OpenApi` and copy the dll to `Aliencube.AzureFunctions.FunctionAppV2`, add the nuget package for `Aliencube.AzureFunctions.Extensions.DependencyInjection` to csproj and it ends up looking like this it works

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aliencube.AzureFunctions.Extensions.DependencyInjection" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Aliencube.AzureFunctions.FunctionAppCommon"/>
    <Reference Include="Aliencube.AzureFunctions.Extensions.OpenApi"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

That just makes it even weirder that my other project does not work as that is pretty much a copy paste from this.

If using VS Code:

launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to C# Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}"
          }
    ]
}
```

tasks.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet build",
            "type": "shell",
            "group": "build",
            "options": {
                "cwd": "${workspaceFolder}/src/Aliencube.AzureFunctions.FunctionAppV2"
              },            
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
        {
          "label": "runFunctionsHost",
          "type": "shell",
          "dependsOn": "build",
          "options": {
            "cwd": "${workspaceFolder}/src/Aliencube.AzureFunctions.FunctionAppV2/bin/Debug/netstandard2.0"
          },
          "command": "func host start",
          "isBackground": true,
          "problemMatcher": "$func-watch"
        }
    ]
}
```

**Comment by spaelling** [comment]
I had 2 references to `Aliencube.AzureFunctions.Extensions.OpenApi` - removing the `PackageReference` and it works. I would expect some sort of warning or error, but there was none.

`<PackageReference Include="Aliencube.AzureFunctions.Extensions.OpenApi" Version="1.2.0" />`
and
`<Reference Include="Aliencube.AzureFunctions.Extensions.OpenApi"/>`

Still great work. I will test again in the next version and work with this for now.

**Comment by spaelling** [comment]
It does not render swagger.json. Any idea on how to go about debugging this?

**Comment by spaelling** [comment]
I found the issue.

In `GetOpenApiOperation` I amended the code to

```
            var op = element.GetOpenApiOperation();
            if(op == null)
            {

                return new OpenApiOperation();
            }
```

I guess this is because I do not have all functions (operations) annotated. In that case this throws an exception because op is `null`

```
            var operation = new OpenApiOperation()
                                {
                                    OperationId = string.IsNullOrWhiteSpace(op.OperationId) ? $"{function.Name}_{verb}" : op.OperationId,
                                    Tags = op.Tags.Select(p => new OpenApiTag() { Name = p }).ToList(),
                                    Summary = op.Summary
                                };
```

**Comment by justinyoo** [comment]
If you've checked out the `master` branch, `Aliencube.AzureFunctions.Extensions.FunctionAppCommon` shouldn't exist, because it only stays in the `dev` branch. As of today, the `master` branch is a snapshot of `swagger-1.3.0`, which is the latest release of [`Aliencube.AzureFunctions.Extensions.OpenApi` 1.3.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.3.0).

If you still see `Aliencube.AzureFunctions.Extensions.FunctionAppCommon`, even after you've checked out the `master` branch, your local branch has been messed up for some reason.

I would recommend you to:
1. Clone a fresh one,
1. Check out the `master` branch`,
1. Build it, and
1. Run it.

**Comment by spaelling** [comment]
not sure why I have cloned the dev branch. Did not even realize. You may still need to add some code to

[DocumentHelper.cs](https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/src/Aliencube.AzureFunctions.Extensions.OpenApi/DocumentHelper.cs#L81)

```
            if(op == null)
            {

                return new OpenApiOperation();
            }
```

I will have a look at the master branch. The link on Github points to the dev branch it seems. So will have to instruct git to specifically target the master branch.

**Comment by justinyoo** [comment]
Thanks for the code snippet. I'll definitely have a look.

As the `master` branch to me is really a snapshot of each library release, nothing more than that, and the `dev` branch reflects the latest update and/or activities of this repository. Therefore, setting the `dev` branch as a default view makes much more sense to me, and probably others who are familiar with branching strategy.

Anyway, I'll close this issue and create another one for your concern around `DocumentHelper`.

**Comment by spaelling** [comment]
> Thanks for the code snippet. I'll definitely have a look.
> 
> As the `master` branch to me is really a snapshot of each library release, nothing more than that, and the `dev` branch reflects the latest update and/or activities of this repository. Therefore, setting the `dev` branch as a default view makes much more sense to me, and probably others who are familiar with branching strategy.
> 
> Anyway, I'll close this issue and create another one for your concern around `DocumentHelper`.

Fine by me. We worked it out after all, and I have a better understanding of how all of this works. I have no experience with Swagger other than a consumer of APIs.

Good point with the branching. Maybe put a disclaimer on top of the readme.md that the default branch is the dev branch?
