### ISSUE TITLE
Interface name is misspelled

### ISSUE THREAD

**Issue by oising** [aliencube/AzureFunctions.Extensions#80]
https://github.com/aliencube/AzureFunctions.Extensions/blob/19c7c188b3e0d8cb1d2546bfd92f47d9948a6e91/src/Aliencube.AzureFunctions.FunctionAppCommon/Functions/IRenderOpeApiDocumentFunction.cs#L10

Missing the 'n' in Open.

IRenderOpe>n<ApiDocumentFunction

**Comment by justinyoo** [comment]
@oising Thanks for the issue! The sample code has been revamped.
