### ISSUE TITLE
Enum values not showing in rendered document

### ISSUE THREAD

**Issue by michaelstaszewski** [aliencube/AzureFunctions.Extensions#81]
This is related to #26 and #33.

I have an enum defined as follows...

```csharp
[JsonConverter(typeof(StringEnumConverter))]
public enum Architecture
{
    X86 = 0,
    X64 = 1,
    Arm = 2,
    Arm64 = 3
}
```

I've decorated my function to include a parameter definition like so...

```csharp
[OpenApiParameter(name: "architecture", In = ParameterLocation.Query, Required = false, Type = typeof(Architecture))]
```

The resulting OpenAPI definition comes out like so...

```json
{
    "name": "architecture",
    "in": "query",
    "schema": {
        "type": "integer",
        "format": "int32"
    }
}
```

What am I missing there to get the parameter to report that it's an enum and its allowed values instead of int?

Thanks,
Michael

**Comment by justinyoo** [comment]
@michaelstaszewski Thanks for your comment!

Just to confirm, do you also have the same issue when your enum is a part of the request/response payload?

**Comment by justinyoo** [comment]
Please refer to the discussion at #75
