### ISSUE TITLE
Publish symbols

### ISSUE THREAD

**Issue by eisber** [aliencube/AzureFunctions.Extensions#85]
Hi,

Any chance you can publish the symbols too? 
https://geeklearning.io/how-to-debug-a-net-core-nuget-package/

Markus

**Comment by justinyoo** [comment]
@eisber Thanks for the issue. Let me double check.

**Comment by justinyoo** [comment]
This has been fixed at #88 and will be released soon. Due to this change, all NuGet packages will have its slight version up.
