### ISSUE TITLE
Dependency problem when installing 1.6

### ISSUE THREAD

**Issue by natiox** [aliencube/AzureFunctions.Extensions#87]
Wants Aliencube.AzureFunctions.Extensions.Configuration.AppSettings (>= 1.6.0) but there's no such thing in NuGet.

**Comment by justinyoo** [comment]
@natiox Oops I'll check this out.

**Comment by justinyoo** [comment]
New version 1.6.1 has been released. Thanks!

https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.6.1
