### ISSUE TITLE
Swagger endpoints result in 401 when hosting in Azure

### ISSUE THREAD

**Issue by 1TheMuffinMan** [aliencube/AzureFunctions.Extensions#95]
I have the newest nuget package and am using your openapi/swagger document generation code. It works in localhost, but when I deploy to Azure I just get a 401 response when I access `/api/swagger/ui`

Any idea?

**Comment by justinyoo** [comment]
@1TheMuffinMan Hi, did you get a chance to put this? https://github.com/aliencube/AzureFunctions.Extensions/blob/dev/docs/openapi.md#configure-app-settings-key

**Comment by 1TheMuffinMan** [comment]
I took the value from `_master` and put it in the `OpenApi__ApiKey` in `local.settings.json` and also in the Application settings in Azure. Still 401.

![image](https://user-images.githubusercontent.com/4889283/87764460-464d9700-c7cb-11ea-9093-c2ed33864455.png)

![image](https://user-images.githubusercontent.com/4889283/87764496-5796a380-c7cb-11ea-9271-ea73843df9e4.png)

![image](https://user-images.githubusercontent.com/4889283/87764570-7d23ad00-c7cb-11ea-89f7-011c4f452abd.png)

Thank you for your help.

**Comment by justinyoo** [comment]
Your Swagger endpoint should also be with the key like `/api/swagger/ui?code=xxxx`. Please try this and let me know.

**Comment by 1TheMuffinMan** [comment]
Thank you, got it working!

**Comment by justinyoo** [comment]
Glad it works!
