### ISSUE TITLE
OpenApiResponseWithoutBodyAttribute example is incorrect

### ISSUE THREAD

**Issue by kylednoland** [aliencube/AzureFunctions.Extensions#98]
## Reproduction Steps
The documentation for `openapi.md` includes examples for all of the supported decorators. The code snippet example for for `OpenApiResponseWithoutBodyAttribute` includes incorrect parameters which I believe are incorrectly for the `OpenApiResponseWithBodyAttribute` decorator instead.

## Proposed Solution
- Remove the `contentType` and `bodyType` parameters from the `OpenApiResponseWithoutBodyAttribute` decorator example.

**Comment by justinyoo** [comment]
@kylednoland Thanks for picking up the typo!
